GET http://localhost:3000/user

###
POST http://localhost:3000/user
content-type: application/json

{
  "name": "Eliane",
  "email": "hudson@teste.com",
  "phone": "84988385145",
  "cpf": "12345678920",
  "password": "senha nova"
}